eureka:
    client:
        fetchRegistry: true
        preferIpAddress: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://eurekaserver:8090/eureka/
server:
    port: 8091

spring:
    rabbitmq:
        host: localhost
        password: '{cipher}87dd3fd18f40f34aae66e2a03004cc5b67d9f36c1a8e8aee7beeb943caa238e3'
        port: 5672
        username: guest
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        baseUrl: http://localhost:9411/
        rabbitmq:
            queue: zipkin
        sender:
            type: rabbit
management:
    endpoint:
        shutdown:
            enabled: true
    auditevents:
        enabled: true
    endpoints:
        web:
            exposure:
                include: '*'

info:
    app:
        description: Bank System Gateway Application
        name: Gateway Server Bank System Microservice
        version: 1.0.0
logging:
    level:
        com:
            banksystem:
                gatewayserver: DEBUG