eureka:
    client:
        fetchRegistry: true
        preferIpAddress: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://eurekaserver:8090/eureka/
server:
    port: 8091

spring:
    #rabbitmq:
        #host: rabbitmq

        #password: '{cipher}87dd3fd18f40f34aae66e2a03004cc5b67d9f36c1a8e8aee7beeb943caa238e3'
        #port: 5672
       # username: guest
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        baseUrl: http://localhost:9411/
        #rabbitmq:
            #queue: zipkin
        #sender:
           # type: rabbit
    security:
        oauth2:
            client:
                provider:
                    keycloack:
                        tokenUri: http://localhost:8080/realms/master/protocol/openid-connect/token
                        authorizationUri: http://localhost:8080/realms/master/protocol/openid-connect/auth
                        userInfoUri: http://localhost:8080/realms/master/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username
                registration:
                    banksystem-gateway:
                        provider: keycloack
                        clientId: banksystemgatewayui
                        clientSecret: xE1EGdqNAXPPxzjtd8nXFsnIInRw4VX2
                        authorizationGrantType: authorization_code
                        redirectUri: http://127.0.0.1:8091/login/oauth2/code/keycloak
                        #redirectUri: http://gatewayserver:8091/login/oauth2/code/keycloak
    logging:
        level:
            org:
                springframework:
                    security: DEBUG
management:
    endpoint:
        shutdown:
            enabled: true
    auditevents:
        enabled: true
    endpoints:
        web:
            exposure:
                include: '*'

info:
    app:
        description: Bank System Gateway Application
        name: Gateway Server Bank System Microservice
        version: 1.0.0
logging:
    level:
        com:
            banksystem:
                gatewayserver: DEBUG