spring:
    datasource:
        password: '{cipher}c6f5efdeb26b003bfdb8608d9db613d5cfa2d870df3ceeaec64c77a64ecb992f'
        url: jdbc:mysql://mysqldb/loans?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        username: '{cipher}c6f5efdeb26b003bfdb8608d9db613d5cfa2d870df3ceeaec64c77a64ecb992f'
    jpa:
        databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    rabbitmq:
        host: localhost
        password: '{cipher}87dd3fd18f40f34aae66e2a03004cc5b67d9f36c1a8e8aee7beeb943caa238e3'
        port: 5672
        username: guest
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        baseUrl: http://localhost:9411/
        rabbitmq:
            queue: zipkin
        sender:
            type: rabbit
